### ISSUE TITLE
Change the mouse when it is placed on toggle button

### ISSUE THREAD

**Issue by IC1101Virgo** [IC1101Virgo/Care-To-Share#20]
The mouse currently changes to text curser. Change it to a hand or something different 🌷 
https://ic1101virgo.github.io/Care-To-Share/ 
Check the website to understand.

**Comment by ankitgauri26** [comment]
@IC1101Virgo  - What I understand is when you move your cursor to any text, it changes to text cursor and you want to change it Hand or something different? Because when you take you cursor to any link, it is changing to Hand. You want the same behaviour when you take the cursor to any text? Please confirm. Happy to work on this

**Comment by tanishbaansal** [comment]
@IC1101Virgo i can change the cursor for text cursor to hand . Can you assign me this issue .

**Comment by IC1101Virgo** [comment]
@ankitgauri26 Yes something of that sort. Please go ahead you are open to imagination 😉 ! 
@tanishbaansal There are more issues coming up keep an eye on them 👁️ !

**Comment by ankitgauri26** [comment]
@IC1101Virgo - Thank you for assigning the issue.
I have created a new branch "dev" and created a pull request after adding new cursor.
